version: '3.8'

services:
  postgres_db:
    image: postgres:14-alpine
    container_name: postgres-db-container
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=tasktracer_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d tasktracer_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  authservice:
    image: serhatsdocker/tasktracer-authservice:latest
    container_name: auth-service-container
    restart: always
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__AuthDbConnection=Host=postgres_db;Port=5432;Database=tasktracer_db;Username=admin;Password=mysecretpassword
      - Jwt__Key=İnternetProgramlamaİcinCokGizliBirKeyYazdimBunuKimseylePaylasamamLutfenBendenIstemeCunkuCokCokGizli
      - Jwt__Issuer=TaskTracer.AuthService
      - Jwt__Audience=TaskTracer.ApiClients
    depends_on:
      postgres_db:
        condition: service_healthy

  userservice:
    image: serhatsdocker/tasktracer-userservice:latest
    container_name: user-service-container
    restart: always
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__UserDbConnection=Host=postgres_db;Port=5432;Database=tasktracer_db;Username=admin;Password=mysecretpassword
      - Jwt__Key=İnternetProgramlamaİcinCokGizliBirKeyYazdimBunuKimseylePaylasamamLutfenBendenIstemeCunkuCokCokGizli
      - Jwt__Issuer=TaskTracer.AuthService
      - Jwt__Audience=TaskTracer.ApiClients
    depends_on:
      postgres_db:
        condition: service_healthy

  taskservice:
    image: serhatsdocker/tasktracer-taskservice:latest
    container_name: task-service-container
    restart: always
    ports:
      - "5003:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__TaskDbConnection=Host=postgres_db;Port=5432;Database=tasktracer_db;Username=admin;Password=mysecretpassword
      - Jwt__Key=İnternetProgramlamaİcinCokGizliBirKeyYazdimBunuKimseylePaylasamamLutfenBendenIstemeCunkuCokCokGizli
      - Jwt__Issuer=TaskTracer.AuthService
      - Jwt__Audience=TaskTracer.ApiClients
    depends_on:
      postgres_db:
        condition: service_healthy

  apigateway:
    image: serhatsdocker/tasktracer-apigateway:latest
    container_name: api-gateway-container
    restart: always
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - authservice
      - userservice
      - taskservice

  frontend:
    image: serhatsdocker/tasktracer-frontend:latest
    container_name: frontend-container
    restart: always
    ports:
      - "3000:80"
    build:
      context: ./task-ui
      args:
       - REACT_APP_API_BASE_URL
    
    depends_on:
      - apigateway

volumes:
  postgres_data:
