name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push AuthService
        uses: docker/build-push-action@v4
        with:
          context: ./TaskTracerMicroservices/TaskTracer.AuthService
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tasktracer-authservice:latest

      - name: Build and push UserService
        uses: docker/build-push-action@v4
        with:
          context: ./TaskTracerMicroservices/TaskTracer.UserService
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tasktracer-userservice:latest

      - name: Build and push TaskService
        uses: docker/build-push-action@v4
        with:
          context: ./TaskTracerMicroservices/TaskTracer.TaskService
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tasktracer-taskservice:latest

      - name: Build and push ApiGateway
        uses: docker/build-push-action@v4
        with:
          context: ./TaskTracerMicroservices/TaskTracer.ApiGateway
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tasktracer-apigateway:latest

      - name: Build and push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./task-ui
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tasktracer-frontend:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          script: |
            cd ~/TaskTracer
            git pull origin main
            docker compose pull
            docker compose up -d
            docker image prune -f
